### ISSUE TITLE
Is it a good idea to use a GitHub Action in demo workflow?

### ISSUE THREAD

**Issue by limonte** [RobinTail/incaseofmydeath#996]
Thank you for the amazing project 🙌  It's a god idea to keep death in mind, it'll come in the least expected moment.

Considering the fact that GitHub Actions aren't safe by default, is it a good idea to demonstrate sending emails with `dawidd6/action-send-mail`?

In theory, nothing prevents the author of that action from publishing a vulnerable tag ([read more](https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash)) and getting access to my emails including secret variables in them.

The safer alternative would be to use commit hash. Or, maybe there's some nice CLI solution without using any custom GitHub actions?

Thanks again and have a great day!

**Comment by RobinTail** [comment]
The particular mail sending action is a third-party software included in Readme for the demonstration purposes only.
I've just taken the first one I found in the directory.
Users should decide on their own which actions to choose.

However, I agree that it should be better clarified.
Thank you, @limonte
